
using AdvanceCRM.Administration;
using Dapper;
using FluentMigrator;
using FluentMigrator.Builders.Create.Table;
using Serenity.Data;
using System;
using System.Collections.Generic;
using Serenity.Abstractions;
using Serenity.Extensions.DependencyInjection;
using System.Linq;
using System.Web;

namespace AdvanceCRM.Migrations.DefaultDB
{
    [Migration(20250104092600)]
    public class DefaultDB_20250104_092600_State_City_Insert : Migration
    {
        public override void Up()
        {
            // Handle State table
            if (!Schema.Table("State").Exists())
            {
                Create.Table("State")
                    .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                    .WithColumn("State").AsString(100).NotNullable();

                InsertStates();
            }
            else if (!DoesRecordsExist("State"))
            {
                InsertStates();
            }

            // Handle City table
            if (!Schema.Table("City").Exists())
            {
                Create.Table("City")
                    .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                    .WithColumn("City").AsString(100).NotNullable()
                    .WithColumn("StateId").AsInt32().ForeignKey("State", "Id");

                InsertCities();
            }
            else if (!DoesRecordsExist("City"))
            {
                InsertCities();
            }
        }

        public override void Down()
        {
            // Drop City table
            if (Schema.Table("City").Exists())
            {
                Delete.Table("City");
            }

            // Drop State table
            if (Schema.Table("State").Exists())
            {
                Delete.Table("State");
            }
        }


        private void InsertStates()
        {
            Execute.Sql("SET IDENTITY_INSERT [dbo].[State] ON;");

            Insert.IntoTable("State").Row(new { Id = 1, State = "Maharashtra" });
            Insert.IntoTable("State").Row(new { Id = 2, State = "Gujarat" });
            Insert.IntoTable("State").Row(new { Id = 3, State = "Andaman Nicobar" });
            Insert.IntoTable("State").Row(new { Id = 4, State = "Andhra Pradesh" });
            Insert.IntoTable("State").Row(new { Id = 5, State = "Arunachal Pradesh" });
            Insert.IntoTable("State").Row(new { Id = 6, State = "Assam" });
            Insert.IntoTable("State").Row(new { Id = 7, State = "Bihar" });
            Insert.IntoTable("State").Row(new { Id = 8, State = "Chandigarh" });
            Insert.IntoTable("State").Row(new { Id = 9, State = "Chhattisgarh" });
            Insert.IntoTable("State").Row(new { Id = 10, State = "Dadra Nagar Haveli" });
            Insert.IntoTable("State").Row(new { Id = 11, State = "Daman Diu" });
            Insert.IntoTable("State").Row(new { Id = 12, State = "Delhi" });
            Insert.IntoTable("State").Row(new { Id = 13, State = "Goa" });
            Insert.IntoTable("State").Row(new { Id = 14, State = "Gujarat" });
            Insert.IntoTable("State").Row(new { Id = 15, State = "Haryana" });
            Insert.IntoTable("State").Row(new { Id = 16, State = "Himachal Pradesh" });
            Insert.IntoTable("State").Row(new { Id = 17, State = "Jammu Kashmir" });
            Insert.IntoTable("State").Row(new { Id = 18, State = "Jharkhand" });
            Insert.IntoTable("State").Row(new { Id = 19, State = "Karnataka" });
            Insert.IntoTable("State").Row(new { Id = 20, State = "Kerala" });
            Insert.IntoTable("State").Row(new { Id = 21, State = "Ladakh" });
            Insert.IntoTable("State").Row(new { Id = 22, State = "Lakshadweep" });
            Insert.IntoTable("State").Row(new { Id = 23, State = "Madhya Pradesh" });
            Insert.IntoTable("State").Row(new { Id = 24, State = "Manipur" });
            Insert.IntoTable("State").Row(new { Id = 25, State = "Meghalaya" });
            Insert.IntoTable("State").Row(new { Id = 26, State = "Mizoram" });
            Insert.IntoTable("State").Row(new { Id = 27, State = "Nagaland" });
            Insert.IntoTable("State").Row(new { Id = 28, State = "Odisha" });
            Insert.IntoTable("State").Row(new { Id = 29, State = "Puducherry" });
            Insert.IntoTable("State").Row(new { Id = 30, State = "Punjab" });
            Insert.IntoTable("State").Row(new { Id = 31, State = "Rajasthan" });
            Insert.IntoTable("State").Row(new { Id = 32, State = "Sikkim" });
            Insert.IntoTable("State").Row(new { Id = 33, State = "Tamil Nadu" });
            Insert.IntoTable("State").Row(new { Id = 34, State = "Telangana" });
            Insert.IntoTable("State").Row(new { Id = 35, State = "Tripura" });
            Insert.IntoTable("State").Row(new { Id = 36, State = "Uttar Pradesh" });
            Insert.IntoTable("State").Row(new { Id = 37, State = "Uttarakhand" });
            Insert.IntoTable("State").Row(new { Id = 38, State = "West Bengal" });
            Execute.Sql("SET IDENTITY_INSERT [dbo].[State] OFF;");

        }

        private void InsertCities()
        {
            Execute.Sql("SET IDENTITY_INSERT [dbo].[City] ON;");

            Insert.IntoTable("City").Row(new { Id = 7, City = "North Middle AndamaCityName ", StateId = 3 });
            Insert.IntoTable("City").Row(new { Id = 8, City = "South AndamaCityName ", StateId = 3 });
            Insert.IntoTable("City").Row(new { Id = 9, City = "Chittoor", StateId = 4 });
            Insert.IntoTable("City").Row(new { Id = 10, City = "East davari", StateId = 4 });
            Insert.IntoTable("City").Row(new { Id = 11, City = "Guntur", StateId = 4 });
            Insert.IntoTable("City").Row(new { Id = 12, City = "Kadapa", StateId = 4 });
            Insert.IntoTable("City").Row(new { Id = 13, City = "Krishna", StateId = 4 });
            Insert.IntoTable("City").Row(new { Id = 14, City = "Kurnool", StateId = 4 });
            Insert.IntoTable("City").Row(new { Id = 15, City = "Nellore", StateId = 4 });
            Insert.IntoTable("City").Row(new { Id = 16, City = "Prakasam", StateId = 4 });
            Insert.IntoTable("City").Row(new { Id = 17, City = "Srikakulam", StateId = 4 });
            Insert.IntoTable("City").Row(new { Id = 18, City = "Visakhapatnam", StateId = 4 });
            Insert.IntoTable("City").Row(new { Id = 19, City = "Vizianagaram", StateId = 4 });
            Insert.IntoTable("City").Row(new { Id = 20, City = "West davari", StateId = 4 });
            Insert.IntoTable("City").Row(new { Id = 21, City = "Central Siang", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 22, City = "Changlang", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 23, City = "Dibang Valley", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 24, City = "East Kameng", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 25, City = "East Siang", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 26, City = "Kamle", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 27, City = "Kra Daadi", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 28, City = "Kurung Kumey", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 29, City = "Lepa Rada", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 30, City = "Lohit", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 31, City = "Longding", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 32, City = "Lower Dibang Valley", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 33, City = "Lower Siang", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 34, City = "Lower Subansiri", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 35, City = "Namsai", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 36, City = "Pakke Kessang", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 37, City = "Papum Pare", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 38, City = "Shi Yomi", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 39, City = "Tawang", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 40, City = "Tirap", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 41, City = "Upper Siang", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 42, City = "Upper Subansiri", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 43, City = "West Kameng", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 44, City = "West Siang", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 45, City = "Baksa", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 46, City = "Barpeta", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 47, City = "Biswanath", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 48, City = "BongaigaoCityName ", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 49, City = "Cachar", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 50, City = "Charaideo", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 51, City = "Chirang", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 52, City = "Darrang", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 53, City = "Dhemaji", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 54, City = "Dhubri", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 55, City = "Dibrugarh", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 56, City = "Dima Hasao", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 57, City = "alpara", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 58, City = "laghat", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 59, City = "Hailakandi", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 60, City = "Hojai", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 61, City = "Jorhat", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 62, City = "Kamrup", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 63, City = "Kamrup MetropolitaCityName ", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 64, City = "Karbi Anglong", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 65, City = "Karimganj", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 66, City = "Kokrajhar", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 67, City = "Lakhimpur", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 68, City = "Majuli", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 69, City = "MorigaoCityName ", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 70, City = "NagaoCityName ", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 71, City = "Nalbari", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 72, City = "Sivasagar", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 73, City = "Sonitpur", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 74, City = "South Salmara-Mankachar", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 75, City = "Tinsukia", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 76, City = "Udalguri", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 77, City = "West Karbi Anglong", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 78, City = "Arwal", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 79, City = "Aurangabad", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 80, City = "Banka", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 81, City = "Begusarai", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 82, City = "Bhagalpur", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 83, City = "Bhojpur", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 84, City = "Buxar", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 85, City = "Darbhanga", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 86, City = "East ChamparaCityName ", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 87, City = "Gaya", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 88, City = "palganj", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 89, City = "Jamui", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 90, City = "Jehanabad", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 91, City = "Kaimur", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 92, City = "Katihar", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 93, City = "Khagaria", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 94, City = "Kishanganj", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 95, City = "Lakhisarai", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 96, City = "Madhepura", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 97, City = "Madhubani", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 98, City = "Munger", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 99, City = "Muzaffarpur", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 100, City = "Nalanda", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 101, City = "Nawada", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 102, City = "Patna", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 103, City = "Purnia", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 104, City = "Rohtas", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 105, City = "Saharsa", StateId = 7 });
            
            Insert.IntoTable("City").Row(new { Id = 106, City = "Samastipur", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 107, City = "SaraCityName ", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 108, City = "Sheikhpura", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 109, City = "Sheohar", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 110, City = "Sitamarhi", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 111, City = "SiwaCityName ", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 112, City = "Supaul", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 113, City = "Vaishali", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 114, City = "West ChamparaCityName ", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 115, City = "Baloda Bazar", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 116, City = "Balrampur", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 117, City = "Bastar", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 118, City = "Bemetara", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 119, City = "Bijapur", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 120, City = "Bilaspur", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 121, City = "Dantewada", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 122, City = "Dhamtari", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 123, City = "Durg", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 124, City = "Gariaband", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 125, City = "Gaurela Pendra Marwahi", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 126, City = "Janjgir Champa", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 127, City = "Jashpur", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 128, City = "Kabirdham", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 129, City = "Kanker", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 130, City = "KondagaoCityName ", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 131, City = "Korba", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 132, City = "Koriya", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 133, City = "Mahasamund", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 134, City = "Mungeli", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 135, City = "Narayanpur", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 136, City = "Raigarh", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 137, City = "Raipur", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 138, City = "RajnandgaoCityName ", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 139, City = "Sukma", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 140, City = "Surajpur", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 141, City = "Surguja", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 142, City = "Diu", StateId = 11 });
            Insert.IntoTable("City").Row(new { Id = 143, City = "East Delhi", StateId = 12 });
            Insert.IntoTable("City").Row(new { Id = 144, City = "New Delhi", StateId = 12 });
            Insert.IntoTable("City").Row(new { Id = 145, City = "North Delhi", StateId = 12 });
            Insert.IntoTable("City").Row(new { Id = 146, City = "North East Delhi", StateId = 12 });
            Insert.IntoTable("City").Row(new { Id = 147, City = "North West Delhi", StateId = 12 });
            Insert.IntoTable("City").Row(new { Id = 148, City = "Shahdara", StateId = 12 });
            Insert.IntoTable("City").Row(new { Id = 149, City = "South Delhi", StateId = 12 });
            Insert.IntoTable("City").Row(new { Id = 150, City = "South East Delhi", StateId = 12 });
            Insert.IntoTable("City").Row(new { Id = 151, City = "South West Delhi", StateId = 12 });
            Insert.IntoTable("City").Row(new { Id = 152, City = "West Delhi", StateId = 12 });
            Insert.IntoTable("City").Row(new { Id = 153, City = "South a", StateId = 13 });
            Insert.IntoTable("City").Row(new { Id = 154, City = "Amreli", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 155, City = "Anand", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 156, City = "Aravalli", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 157, City = "Banaskantha", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 158, City = "Bharuch", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 159, City = "Bhavnagar", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 160, City = "Botad", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 161, City = "Chhota Udaipur", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 162, City = "Dahod", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 163, City = "Dang", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 164, City = "Devbhoomi Dwarka", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 165, City = "Gandhinagar", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 166, City = "Gir Somnath", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 167, City = "Jamnagar", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 168, City = "Junagadh", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 169, City = "Kheda", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 170, City = "Kutch", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 171, City = "Mahisagar", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 172, City = "Mehsana", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 173, City = "Morbi", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 174, City = "Narmada", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 175, City = "Navsari", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 176, City = "Panchmahal", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 177, City = "PataCityName ", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 178, City = "Porbandar", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 179, City = "Rajkot", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 180, City = "Sabarkantha", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 181, City = "Surat", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 182, City = "Surendranagar", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 183, City = "Tapi", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 184, City = "Vadodara", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 185, City = "Valsad", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 186, City = "Bhiwani", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 187, City = "Charkhi Dadri", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 188, City = "Faridabad", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 189, City = "Fatehabad", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 190, City = "Gurugram", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 191, City = "Hisar", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 192, City = "Jhajjar", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 193, City = "Jind", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 194, City = "Kaithal", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 195, City = "Karnal", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 196, City = "Kurukshetra", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 197, City = "Mahendragarh", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 198, City = "Mewat", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 199, City = "Palwal", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 200, City = "Panchkula", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 201, City = "Panipat", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 202, City = "Rewari", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 203, City = "Rohtak", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 204, City = "Sirsa", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 205, City = "Sonipat", StateId = 15 });
            
Insert.IntoTable("City").Row(new { Id = 206, City = "Yamunanagar", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 207, City = "Chamba", StateId = 16 });
            Insert.IntoTable("City").Row(new { Id = 208, City = "Hamirpur", StateId = 16 });
            Insert.IntoTable("City").Row(new { Id = 209, City = "Kangra", StateId = 16 });
            Insert.IntoTable("City").Row(new { Id = 210, City = "Kinnaur", StateId = 16 });
            Insert.IntoTable("City").Row(new { Id = 211, City = "Kullu", StateId = 16 });
            Insert.IntoTable("City").Row(new { Id = 212, City = "Lahaul Spiti", StateId = 16 });
            Insert.IntoTable("City").Row(new { Id = 213, City = "Mandi", StateId = 16 });
            Insert.IntoTable("City").Row(new { Id = 214, City = "Shimla", StateId = 16 });
            Insert.IntoTable("City").Row(new { Id = 215, City = "Sirmaur", StateId = 16 });
            Insert.IntoTable("City").Row(new { Id = 216, City = "SolaCityName ", StateId = 16 });
            Insert.IntoTable("City").Row(new { Id = 217, City = "Una", StateId = 16 });
            Insert.IntoTable("City").Row(new { Id = 218, City = "Bandipora", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 219, City = "Baramulla", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 220, City = "Budgam", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 221, City = "Doda", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 222, City = "Ganderbal", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 223, City = "Jammu", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 224, City = "Kathua", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 225, City = "Kishtwar", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 226, City = "Kulgam", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 227, City = "Kupwara", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 228, City = "Poonch", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 229, City = "Pulwama", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 230, City = "Rajouri", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 231, City = "RambaCityName ", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 232, City = "Reasi", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 233, City = "Samba", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 234, City = "ShopiaCityName ", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 235, City = "Srinagar", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 236, City = "Udhampur", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 237, City = "Chatra", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 238, City = "Deoghar", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 239, City = "Dhanbad", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 240, City = "Dumka", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 241, City = "East Singhbhum", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 242, City = "Garhwa", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 243, City = "Giridih", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 244, City = "dda", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 245, City = "Gumla", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 246, City = "Hazaribagh", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 247, City = "Jamtara", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 248, City = "Khunti", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 249, City = "Koderma", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 250, City = "Latehar", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 251, City = "Lohardaga", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 252, City = "Pakur", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 253, City = "Palamu", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 254, City = "Ramgarh", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 255, City = "Ranchi", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 256, City = "Sahebganj", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 257, City = "Seraikela KharsawaCityName ", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 258, City = "Simdega", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 259, City = "West Singhbhum", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 260, City = "Bangalore Rural", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 261, City = "Bangalore UrbaCityName ", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 262, City = "Belgaum", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 263, City = "Bellary", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 264, City = "Bidar", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 265, City = "Chamarajanagar", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 266, City = "Chikkaballapur", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 267, City = "Chikkamagaluru", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 268, City = "Chitradurga", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 269, City = "Dakshina Kannada", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 270, City = "Davanagere", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 271, City = "Dharwad", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 272, City = "Gadag", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 273, City = "Gulbarga", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 274, City = "HassaCityName ", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 275, City = "Haveri", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 276, City = "Kodagu", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 277, City = "Kolar", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 278, City = "Koppal", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 279, City = "Mandya", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 280, City = "Mysore", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 281, City = "Raichur", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 282, City = "Ramanagara", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 283, City = "Shimoga", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 284, City = "Tumkur", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 285, City = "Udupi", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 286, City = "Uttara Kannada", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 287, City = "Vijayanagara", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 288, City = "Vijayapura", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 289, City = "Yadgir", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 290, City = "Ernakulam", StateId = 20 });
            Insert.IntoTable("City").Row(new { Id = 291, City = "Idukki", StateId = 20 });
            Insert.IntoTable("City").Row(new { Id = 292, City = "Kannur", StateId = 20 });
            Insert.IntoTable("City").Row(new { Id = 293, City = "Kasarad", StateId = 20 });
            Insert.IntoTable("City").Row(new { Id = 294, City = "Kollam", StateId = 20 });
            Insert.IntoTable("City").Row(new { Id = 295, City = "Kottayam", StateId = 20 });
            Insert.IntoTable("City").Row(new { Id = 296, City = "Kozhikode", StateId = 20 });
            Insert.IntoTable("City").Row(new { Id = 297, City = "Malappuram", StateId = 20 });
            Insert.IntoTable("City").Row(new { Id = 298, City = "Palakkad", StateId = 20 });
            Insert.IntoTable("City").Row(new { Id = 299, City = "Pathanamthitta", StateId = 20 });
            Insert.IntoTable("City").Row(new { Id = 300, City = "Thiruvananthapuram", StateId = 20 });
            Insert.IntoTable("City").Row(new { Id = 301, City = "Thrissur", StateId = 20 });
            Insert.IntoTable("City").Row(new { Id = 302, City = "Wayanad", StateId = 20 });
            Insert.IntoTable("City").Row(new { Id = 303, City = "Leh", StateId = 21 });
            Insert.IntoTable("City").Row(new { Id = 304, City = "Alirajpur", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 305, City = "Anuppur", StateId = 23 });
            
Insert.IntoTable("City").Row(new { Id = 306, City = "Ashoknagar", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 307, City = "Balaghat", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 308, City = "Barwani", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 309, City = "Betul", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 310, City = "Bhind", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 311, City = "Bhopal", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 312, City = "Burhanpur", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 313, City = "Chachaura", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 314, City = "Chhatarpur", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 315, City = "Chhindwara", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 316, City = "Damoh", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 317, City = "Datia", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 318, City = "Dewas", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 319, City = "Dhar", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 320, City = "Dindori", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 321, City = "Guna", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 322, City = "Gwalior", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 323, City = "Harda", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 324, City = "Hoshangabad", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 325, City = "Indore", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 326, City = "Jabalpur", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 327, City = "Jhabua", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 328, City = "Katni", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 329, City = "Khandwa", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 330, City = "Kharne", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 331, City = "Maihar", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 332, City = "Mandla", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 333, City = "Mandsaur", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 334, City = "Morena", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 335, City = "Nagda", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 336, City = "Narsinghpur", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 337, City = "Neemuch", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 338, City = "Niwari", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 339, City = "Panna", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 340, City = "RaiseCityName ", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 341, City = "Rajgarh", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 342, City = "Ratlam", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 343, City = "Rewa", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 344, City = "Sagar", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 345, City = "Satna", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 346, City = "Sehore", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 347, City = "Seoni", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 348, City = "Shahdol", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 349, City = "Shajapur", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 350, City = "Sheopur", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 351, City = "Shivpuri", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 352, City = "Sidhi", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 353, City = "Singrauli", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 354, City = "Tikamgarh", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 355, City = "UjjaiCityName ", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 356, City = "Umaria", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 357, City = "Vidisha", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 358, City = "Ahmednagar", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 359, City = "Akola", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 360, City = "Amravati", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 361, City = "Aurangabad", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 362, City = "Beed", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 363, City = "Bhandara", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 364, City = "Buldhana", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 365, City = "Chandrapur", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 366, City = "Dhule", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 367, City = "Gadchiroli", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 368, City = "ndia", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 369, City = "Hinli", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 370, City = "JalgaoCityName ", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 371, City = "Jalna", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 372, City = "Kolhapur", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 373, City = "Latur", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 374, City = "Mumbai City", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 375, City = "Mumbai", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 376, City = "Nagpur", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 377, City = "Nanded", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 378, City = "Nandurbar", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 379, City = "Nashik", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 380, City = "Osmanabad", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 381, City = "Palghar", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 382, City = "Parbhani", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 383, City = "Pune", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 384, City = "Raigad", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 385, City = "Ratnagiri", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 386, City = "Sangli", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 387, City = "Satara", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 388, City = "Sindhudurg", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 389, City = "Solapur", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 390, City = "Thane", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 391, City = "Wardha", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 392, City = "Washim", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 393, City = "Yavatmal", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 394, City = "Chandel", StateId = 24 });
            Insert.IntoTable("City").Row(new { Id = 395, City = "Churachandpur", StateId = 24 });
            Insert.IntoTable("City").Row(new { Id = 396, City = "Imphal East", StateId = 24 });
            Insert.IntoTable("City").Row(new { Id = 397, City = "Imphal West", StateId = 24 });
            Insert.IntoTable("City").Row(new { Id = 398, City = "Jiribam", StateId = 24 });
            Insert.IntoTable("City").Row(new { Id = 399, City = "Kakching", StateId = 24 });
            Insert.IntoTable("City").Row(new { Id = 400, City = "Kamjong", StateId = 24 });
            Insert.IntoTable("City").Row(new { Id = 401, City = "Kangpokpi", StateId = 24 });
            Insert.IntoTable("City").Row(new { Id = 402, City = "Noney", StateId = 24 });
            Insert.IntoTable("City").Row(new { Id = 403, City = "Pherzawl", StateId = 24 });
            Insert.IntoTable("City").Row(new { Id = 404, City = "Senapati", StateId = 24 });
            Insert.IntoTable("City").Row(new { Id = 405, City = "Tamenglong", StateId = 24 });
            
Insert.IntoTable("City").Row(new { Id = 406, City = "Tengnoupal", StateId = 24 });
            Insert.IntoTable("City").Row(new { Id = 407, City = "Thoubal", StateId = 24 });
            Insert.IntoTable("City").Row(new { Id = 408, City = "Ukhrul", StateId = 24 });
            Insert.IntoTable("City").Row(new { Id = 409, City = "East Jaintia Hills", StateId = 25 });
            Insert.IntoTable("City").Row(new { Id = 410, City = "East Khasi Hills", StateId = 25 });
            Insert.IntoTable("City").Row(new { Id = 411, City = "North Garo Hills", StateId = 25 });
            Insert.IntoTable("City").Row(new { Id = 412, City = "Ri Bhoi", StateId = 25 });
            Insert.IntoTable("City").Row(new { Id = 413, City = "South Garo Hills", StateId = 25 });
            Insert.IntoTable("City").Row(new { Id = 414, City = "South West Garo Hills", StateId = 25 });
            Insert.IntoTable("City").Row(new { Id = 415, City = "South West Khasi Hills", StateId = 25 });
            Insert.IntoTable("City").Row(new { Id = 416, City = "West Garo Hills", StateId = 25 });
            Insert.IntoTable("City").Row(new { Id = 417, City = "West Jaintia Hills", StateId = 25 });
            Insert.IntoTable("City").Row(new { Id = 418, City = "West Khasi Hills", StateId = 25 });
            Insert.IntoTable("City").Row(new { Id = 419, City = "Champhai", StateId = 26 });
            Insert.IntoTable("City").Row(new { Id = 420, City = "Hnahthial", StateId = 26 });
            Insert.IntoTable("City").Row(new { Id = 421, City = "Kolasib", StateId = 26 });
            Insert.IntoTable("City").Row(new { Id = 422, City = "Khawzawl", StateId = 26 });
            Insert.IntoTable("City").Row(new { Id = 423, City = "Lawngtlai", StateId = 26 });
            Insert.IntoTable("City").Row(new { Id = 424, City = "Lunglei", StateId = 26 });
            Insert.IntoTable("City").Row(new { Id = 425, City = "Mamit", StateId = 26 });
            Insert.IntoTable("City").Row(new { Id = 426, City = "Saiha", StateId = 26 });
            Insert.IntoTable("City").Row(new { Id = 427, City = "Serchhip", StateId = 26 });
            Insert.IntoTable("City").Row(new { Id = 428, City = "Saitual", StateId = 26 });
            Insert.IntoTable("City").Row(new { Id = 429, City = "Kiphire", StateId = 27 });
            Insert.IntoTable("City").Row(new { Id = 430, City = "Kohima", StateId = 27 });
            Insert.IntoTable("City").Row(new { Id = 431, City = "Longleng", StateId = 27 });
            Insert.IntoTable("City").Row(new { Id = 432, City = "Mokokchung", StateId = 27 });
            Insert.IntoTable("City").Row(new { Id = 433, City = "MoCityName ", StateId = 27 });
            Insert.IntoTable("City").Row(new { Id = 434, City = "Noklak", StateId = 27 });
            Insert.IntoTable("City").Row(new { Id = 435, City = "PereCityName ", StateId = 27 });
            Insert.IntoTable("City").Row(new { Id = 436, City = "Phek", StateId = 27 });
            Insert.IntoTable("City").Row(new { Id = 437, City = "Tuensang", StateId = 27 });
            Insert.IntoTable("City").Row(new { Id = 438, City = "Wokha", StateId = 27 });
            Insert.IntoTable("City").Row(new { Id = 439, City = "Zunheboto", StateId = 27 });
            Insert.IntoTable("City").Row(new { Id = 440, City = "Balangir", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 441, City = "Balasore", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 442, City = "Bargarh", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 443, City = "Bhadrak", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 444, City = "Boudh", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 445, City = "Cuttack", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 446, City = "Debagarh", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 447, City = "Dhenkanal", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 448, City = "Gajapati", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 449, City = "Ganjam", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 450, City = "Jagatsinghpur", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 451, City = "Jajpur", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 452, City = "Jharsuguda", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 453, City = "Kalahandi", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 454, City = "Kandhamal", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 455, City = "Kendrapara", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 456, City = "Kendujhar", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 457, City = "Khordha", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 458, City = "Koraput", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 459, City = "Malkangiri", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 460, City = "Mayurbhanj", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 461, City = "Nabarangpur", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 462, City = "Nayagarh", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 463, City = "Nuapada", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 464, City = "Puri", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 465, City = "Rayagada", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 466, City = "Sambalpur", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 467, City = "Subarnapur", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 468, City = "Sundergarh", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 469, City = "Mahe", StateId = 29 });
            Insert.IntoTable("City").Row(new { Id = 470, City = "Puducherry", StateId = 29 });
            Insert.IntoTable("City").Row(new { Id = 471, City = "Yanam", StateId = 29 });
            Insert.IntoTable("City").Row(new { Id = 472, City = "Barnala", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 473, City = "Bathinda", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 474, City = "Faridkot", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 475, City = "Fatehgarh Sahib", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 476, City = "Fazilka", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 477, City = "Firozpur", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 478, City = "Gurdaspur", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 479, City = "Hoshiarpur", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 480, City = "Jalandhar", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 481, City = "Kapurthala", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 482, City = "Ludhiana", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 483, City = "Mansa", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 484, City = "Moga", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 485, City = "Mohali", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 486, City = "Muktsar", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 487, City = "Pathankot", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 488, City = "Patiala", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 489, City = "Rupnagar", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 490, City = "Sangrur", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 491, City = "Shaheed Bhagat Singh Nagar", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 492, City = "Tarn TaraCityName ", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 493, City = "Alwar", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 494, City = "Banswara", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 495, City = "BaraCityName ", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 496, City = "Barmer", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 497, City = "Bharatpur", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 498, City = "Bhilwara", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 499, City = "Bikaner", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 500, City = "Bundi", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 501, City = "Chittorgarh", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 502, City = "Churu", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 503, City = "Dausa", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 504, City = "Dholpur", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 505, City = "Dungarpur", StateId = 31 });
            
Insert.IntoTable("City").Row(new { Id = 506, City = "Hanumangarh", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 507, City = "Jaipur", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 508, City = "Jaisalmer", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 509, City = "Jalore", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 510, City = "Jhalawar", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 511, City = "Jhunjhunu", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 512, City = "Jodhpur", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 513, City = "Karauli", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 514, City = "Kota", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 515, City = "Nagaur", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 516, City = "Pali", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 517, City = "Pratapgarh", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 518, City = "Rajsamand", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 519, City = "Sawai Madhopur", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 520, City = "Sikar", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 521, City = "Sirohi", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 522, City = "Sri Ganganagar", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 523, City = "Tonk", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 524, City = "Udaipur", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 525, City = "North Sikkim", StateId = 32 });
            Insert.IntoTable("City").Row(new { Id = 526, City = "South Sikkim", StateId = 32 });
            Insert.IntoTable("City").Row(new { Id = 527, City = "West Sikkim", StateId = 32 });
            Insert.IntoTable("City").Row(new { Id = 528, City = "Chengalpattu", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 529, City = "Chennai", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 530, City = "Coimbatore", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 531, City = "Cuddalore", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 532, City = "Dharmapuri", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 533, City = "Dindigul", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 534, City = "Erode", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 535, City = "Kallakurichi", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 536, City = "Kanchipuram", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 537, City = "Kanyakumari", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 538, City = "Karur", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 539, City = "Krishnagiri", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 540, City = "Madurai", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 541, City = "Mayiladuthurai", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 542, City = "Nagapattinam", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 543, City = "Namakkal", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 544, City = "Nilgiris", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 545, City = "Perambalur", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 546, City = "Pudukkottai", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 547, City = "Ramanathapuram", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 548, City = "Ranipet", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 549, City = "Salem", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 550, City = "Sivaganga", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 551, City = "Tenkasi", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 552, City = "Thanjavur", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 553, City = "Theni", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 554, City = "Thoothukudi", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 555, City = "Tiruchirappalli", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 556, City = "Tirunelveli", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 557, City = "Tirupattur", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 558, City = "Tiruppur", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 559, City = "Tiruvallur", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 560, City = "Tiruvannamalai", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 561, City = "Tiruvarur", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 562, City = "Vellore", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 563, City = "Viluppuram", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 564, City = "Virudhunagar", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 565, City = "Bhadradri Kothagudem", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 566, City = "Hyderabad", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 567, City = "Jagtial", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 568, City = "JangaoCityName ", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 569, City = "Jayashankar", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 570, City = "Jogulamba", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 571, City = "Kamareddy", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 572, City = "Karimnagar", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 573, City = "Khammam", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 574, City = "Komaram Bheem", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 575, City = "Mahabubabad", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 576, City = "Mahbubnagar", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 577, City = "Mancherial", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 578, City = "Medak", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 579, City = "Medchal", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 580, City = "Mulugu", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 581, City = "Nagarkurnool", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 582, City = "Nalnda", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 583, City = "Narayanpet", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 584, City = "Nirmal", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 585, City = "Nizamabad", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 586, City = "Peddapalli", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 587, City = "Rajanna Sircilla", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 588, City = "Ranga Reddy", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 589, City = "Sangareddy", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 590, City = "Siddipet", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 591, City = "Suryapet", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 592, City = "Vikarabad", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 593, City = "Wanaparthy", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 594, City = "Warangal Rural", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 595, City = "Warangal UrbaCityName ", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 596, City = "Yadadri Bhuvanagiri", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 597, City = "mati", StateId = 35 });
            Insert.IntoTable("City").Row(new { Id = 598, City = "Khowai", StateId = 35 });
            Insert.IntoTable("City").Row(new { Id = 599, City = "North Tripura", StateId = 35 });
            Insert.IntoTable("City").Row(new { Id = 600, City = "Sepahijala", StateId = 35 });
            Insert.IntoTable("City").Row(new { Id = 601, City = "South Tripura", StateId = 35 });
            Insert.IntoTable("City").Row(new { Id = 602, City = "Unakoti", StateId = 35 });
            Insert.IntoTable("City").Row(new { Id = 603, City = "West Tripura", StateId = 35 });
            Insert.IntoTable("City").Row(new { Id = 604, City = "Aligarh", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 605, City = "Ambedkar Nagar", StateId = 36 });
            
Insert.IntoTable("City").Row(new { Id = 606, City = "Amethi", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 607, City = "Amroha", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 608, City = "Auraiya", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 609, City = "Ayodhya", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 610, City = "Azamgarh", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 611, City = "Baghpat", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 612, City = "Bahraich", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 613, City = "Ballia", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 614, City = "Balrampur", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 615, City = "Banda", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 616, City = "Barabanki", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 617, City = "Bareilly", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 618, City = "Basti", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 619, City = "Bhadohi", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 620, City = "Bijnor", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 621, City = "BudauCityName ", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 622, City = "Bulandshahr", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 623, City = "Chandauli", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 624, City = "Chitrakoot", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 625, City = "Deoria", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 626, City = "Etah", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 627, City = "Etawah", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 628, City = "Farrukhabad", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 629, City = "Fatehpur", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 630, City = "Firozabad", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 631, City = "Gautam Buddha Nagar", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 632, City = "Ghaziabad", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 633, City = "Ghazipur", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 634, City = "nda", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 635, City = "rakhpur", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 636, City = "Hamirpur", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 637, City = "Hapur", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 638, City = "Hardoi", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 639, City = "Hathras", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 640, City = "JalauCityName ", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 641, City = "Jaunpur", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 642, City = "Jhansi", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 643, City = "Kannauj", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 644, City = "Kanpur Dehat", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 645, City = "Kanpur Nagar", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 646, City = "Kasganj", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 647, City = "Kaushambi", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 648, City = "Kheri", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 649, City = "Kushinagar", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 650, City = "Lalitpur", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 651, City = "Lucknow", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 652, City = "Maharajganj", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 653, City = "Mahoba", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 654, City = "Mainpuri", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 655, City = "Mathura", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 656, City = "Mau", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 657, City = "Meerut", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 658, City = "Mirzapur", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 659, City = "Moradabad", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 660, City = "Muzaffarnagar", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 661, City = "Pilibhit", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 662, City = "Pratapgarh", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 663, City = "Prayagraj", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 664, City = "Raebareli", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 665, City = "Rampur", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 666, City = "Saharanpur", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 667, City = "Sambhal", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 668, City = "Sant Kabir Nagar", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 669, City = "Shahjahanpur", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 670, City = "Shamli", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 671, City = "Shravasti", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 672, City = "Siddharthnagar", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 673, City = "Sitapur", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 674, City = "Sonbhadra", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 675, City = "Sultanpur", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 676, City = "Unnao", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 677, City = "Varanasi", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 678, City = "Bageshwar", StateId = 37 });
            Insert.IntoTable("City").Row(new { Id = 679, City = "Chamoli", StateId = 37 });
            Insert.IntoTable("City").Row(new { Id = 680, City = "Champawat", StateId = 37 });
            Insert.IntoTable("City").Row(new { Id = 681, City = "DehraduCityName ", StateId = 37 });
            Insert.IntoTable("City").Row(new { Id = 682, City = "Haridwar", StateId = 37 });
            Insert.IntoTable("City").Row(new { Id = 683, City = "Nainital", StateId = 37 });
            Insert.IntoTable("City").Row(new { Id = 684, City = "Pauri", StateId = 37 });
            Insert.IntoTable("City").Row(new { Id = 685, City = "Pithoragarh", StateId = 37 });
            Insert.IntoTable("City").Row(new { Id = 686, City = "Rudraprayag", StateId = 37 });
            Insert.IntoTable("City").Row(new { Id = 687, City = "Tehri", StateId = 37 });
            Insert.IntoTable("City").Row(new { Id = 688, City = "Udham Singh Nagar", StateId = 37 });
            Insert.IntoTable("City").Row(new { Id = 689, City = "Uttarkashi", StateId = 37 });
            Insert.IntoTable("City").Row(new { Id = 690, City = "Bankura", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 691, City = "Birbhum", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 692, City = "Cooch Behar", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 693, City = "Dakshin Dinajpur", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 694, City = "Darjeeling", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 695, City = "Hooghly", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 696, City = "Howrah", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 697, City = "Jalpaiguri", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 698, City = "Jhargram", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 699, City = "Kalimpong", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 700, City = "Kolkata", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 701, City = "Malda", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 702, City = "Murshidabad", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 703, City = "Nadia", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 704, City = "North 24 Parganas", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 705, City = "Paschim BardhamaCityName ", StateId = 38 });
            
Insert.IntoTable("City").Row(new { Id = 706, City = "Paschim Medinipur", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 707, City = "Purba BardhamaCityName ", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 708, City = "Purba Medinipur", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 709, City = "Purulia", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 710, City = "South 24 Parganas", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 711, City = "Uttar Dinajpur", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 712, City = "Nicobar", StateId = 3 });
            Insert.IntoTable("City").Row(new { Id = 713, City = "Anantapur", StateId = 4 });
            Insert.IntoTable("City").Row(new { Id = 714, City = "Anjaw", StateId = 5 });
            Insert.IntoTable("City").Row(new { Id = 715, City = "Bajali", StateId = 6 });
            Insert.IntoTable("City").Row(new { Id = 716, City = "Araria", StateId = 7 });
            Insert.IntoTable("City").Row(new { Id = 717, City = "Chandigarh", StateId = 8 });
            Insert.IntoTable("City").Row(new { Id = 718, City = "Balod", StateId = 9 });
            Insert.IntoTable("City").Row(new { Id = 719, City = "Dadra Nagar Haveli", StateId = 10 });
            Insert.IntoTable("City").Row(new { Id = 720, City = "DamaCityName ", StateId = 11 });
            Insert.IntoTable("City").Row(new { Id = 721, City = "Central Delhi", StateId = 12 });
            Insert.IntoTable("City").Row(new { Id = 722, City = "North a", StateId = 13 });
            Insert.IntoTable("City").Row(new { Id = 723, City = "Ahmedabad", StateId = 14 });
            Insert.IntoTable("City").Row(new { Id = 724, City = "Ambala", StateId = 15 });
            Insert.IntoTable("City").Row(new { Id = 725, City = "Bilaspur", StateId = 16 });
            Insert.IntoTable("City").Row(new { Id = 726, City = "Anantnag", StateId = 17 });
            Insert.IntoTable("City").Row(new { Id = 727, City = "Bokaro", StateId = 18 });
            Insert.IntoTable("City").Row(new { Id = 728, City = "Bagalkot", StateId = 19 });
            Insert.IntoTable("City").Row(new { Id = 729, City = "Alappuzha", StateId = 20 });
            Insert.IntoTable("City").Row(new { Id = 730, City = "Kargil", StateId = 21 });
            Insert.IntoTable("City").Row(new { Id = 731, City = "Lakshadweep", StateId = 22 });
            Insert.IntoTable("City").Row(new { Id = 732, City = "Agar Malwa", StateId = 23 });
            Insert.IntoTable("City").Row(new { Id = 733, City = "Bishnupur", StateId = 24 });
            Insert.IntoTable("City").Row(new { Id = 734, City = "East Garo Hills", StateId = 25 });
            Insert.IntoTable("City").Row(new { Id = 735, City = "Aizawl", StateId = 26 });
            Insert.IntoTable("City").Row(new { Id = 736, City = "Dimapur", StateId = 27 });
            Insert.IntoTable("City").Row(new { Id = 737, City = "Angul", StateId = 28 });
            Insert.IntoTable("City").Row(new { Id = 738, City = "Karaikal", StateId = 29 });
            Insert.IntoTable("City").Row(new { Id = 739, City = "Amritsar", StateId = 30 });
            Insert.IntoTable("City").Row(new { Id = 740, City = "Ajmer", StateId = 31 });
            Insert.IntoTable("City").Row(new { Id = 741, City = "East Sikkim", StateId = 32 });
            Insert.IntoTable("City").Row(new { Id = 742, City = "Ariyalur", StateId = 33 });
            Insert.IntoTable("City").Row(new { Id = 743, City = "Adilabad", StateId = 34 });
            Insert.IntoTable("City").Row(new { Id = 744, City = "Dhalai", StateId = 35 });
            Insert.IntoTable("City").Row(new { Id = 745, City = "Agra", StateId = 36 });
            Insert.IntoTable("City").Row(new { Id = 746, City = "Almora", StateId = 37 });
            Insert.IntoTable("City").Row(new { Id = 747, City = "Alipurduar", StateId = 38 });
            Insert.IntoTable("City").Row(new { Id = 748, City = "PUNE", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 750, City = "PUNE", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 751, City = "PUNE", StateId = 1 });
            Insert.IntoTable("City").Row(new { Id = 752, City = "Hyderabad", StateId = 33 });
            Execute.Sql("SET IDENTITY_INSERT [dbo].[City] OFF;");


        }


        private bool DoesRecordsExist(string tableName)
        {
            using (var connection = Dependency.Resolve<ISqlConnections>().NewByKey("Default"))
            {
                // Query to check for records in the table
                var query = $"SELECT CASE WHEN EXISTS (SELECT 1 FROM {tableName} WHERE 1=1) THEN 1 ELSE 0 END";
                return connection.ExecuteScalar<int>(query) > 0;
            }
        }




    }
}