// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AdvanceCRM.Web.EF.Models;

#nullable disable

namespace AdvanceCRM.Web.Migrations
{
    [DbContext(typeof(AdvanceCRMContext))]
    partial class AdvanceCRMContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActionDate");

                    b.Property<int>("ActionType")
                        .HasColumnType("int")
                        .HasColumnName("ActionType");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Changes");

                    b.Property<string>("EntityId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("EntityId");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IpAddress");

                    b.Property<string>("RequestedURI")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("RequestedURI");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SessionId");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TableName");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CityName");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CountryName");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.ExcelImport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ExcelImportStatus")
                        .HasColumnType("int")
                        .HasColumnName("ExcelImportStatus");

                    b.Property<string>("FieldMappings")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FieldMappings");

                    b.Property<string>("ImportedData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImportedData");

                    b.Property<string>("ImportedExcelFile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ImportedExcelFile");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("InsertDate");

                    b.Property<int>("InsertUserId")
                        .HasColumnType("int")
                        .HasColumnName("InsertUserId");

                    b.Property<string>("MasterTableName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MasterTableName");

                    b.Property<string>("Remarks")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Remarks");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("TemplateId");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdateUserId");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("ExcelImports");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.ExcelImportTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ExcelMetadata")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ExcelMetadata");

                    b.Property<string>("ExcelSheet")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ExcelSheet");

                    b.Property<string>("FieldMappings")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FieldMappings");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("InsertDate");

                    b.Property<int>("InsertUserId")
                        .HasColumnType("int")
                        .HasColumnName("InsertUserId");

                    b.Property<string>("MasterTableName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MasterTableName");

                    b.Property<string>("Remarks")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Remarks");

                    b.Property<string>("TemplateExcelFile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TemplateExcelFile");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TemplateName");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("ExcelImportTemplates");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.Exceptions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ApplicationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DuplicateCount")
                        .HasColumnType("int");

                    b.Property<int?>("ErrorHash")
                        .HasColumnType("int");

                    b.Property<string>("FullJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HTTPMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Host")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsProtected")
                        .HasColumnType("bit");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SQL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exceptions");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LanguageId = "en",
                            LanguageName = "English"
                        },
                        new
                        {
                            Id = 2,
                            LanguageId = "ru",
                            LanguageName = "Russian"
                        },
                        new
                        {
                            Id = 3,
                            LanguageId = "es",
                            LanguageName = "Spanish"
                        },
                        new
                        {
                            Id = 4,
                            LanguageId = "tr",
                            LanguageName = "Turkish"
                        },
                        new
                        {
                            Id = 5,
                            LanguageId = "de",
                            LanguageName = "German"
                        },
                        new
                        {
                            Id = 6,
                            LanguageId = "zh-CN",
                            LanguageName = "Chinese (Simplified)"
                        },
                        new
                        {
                            Id = 7,
                            LanguageId = "it",
                            LanguageName = "Italian"
                        },
                        new
                        {
                            Id = 8,
                            LanguageId = "pt",
                            LanguageName = "Portuguese"
                        },
                        new
                        {
                            Id = 9,
                            LanguageId = "pt-BR",
                            LanguageName = "Portuguese (Brazil)"
                        },
                        new
                        {
                            Id = 10,
                            LanguageId = "fa",
                            LanguageName = "Farsi"
                        },
                        new
                        {
                            Id = 11,
                            LanguageId = "vi-VN",
                            LanguageName = "Vietnamese (Vietnam)"
                        });
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.MessageLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<short?>("FromMe")
                        .HasColumnType("smallint");

                    b.Property<string>("FromNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Json")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MessageLogs");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.RolePermission", b =>
                {
                    b.Property<long>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RolePermissionId"));

                    b.Property<string>("PermissionKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.SapDatabase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyDB")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CompanyDB");

                    b.Property<string>("DBDriver")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DBDriver");

                    b.Property<string>("DBPassword")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DBPassword");

                    b.Property<string>("DBServerType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DBServerType");

                    b.Property<string>("DBUserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DBUserName");

                    b.Property<string>("LicenseServer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LicenseServer");

                    b.Property<string>("ODBCServer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ODBCServer");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<string>("ServerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ServerName");

                    b.Property<string>("ServerType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ServerType");

                    b.Property<string>("ServiceLayerURL")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ServiceLayerURL");

                    b.Property<string>("ServiceLayerVersion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ServiceLayerVersion");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.ToTable("SapDatabases");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("Company")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InsertUserId")
                        .HasColumnType("int");

                    b.Property<short>("IsActive")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("LastDirectoryUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<string>("UserImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Company = 1,
                            DisplayName = "admin",
                            Email = "admin@dummy.com",
                            InsertDate = new DateTime(2014, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InsertUserId = 1,
                            IsActive = (short)1,
                            PasswordHash = "rfqpSPYs0ekFlPyvIRTXsdhE/qrTHFF+kKsAUla7pFkXL4BgLGlTe89GDX5DBysenMDj8AqbIZPybqvusyCjwQ",
                            PasswordSalt = "hJf_F",
                            Source = "site",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.UserPermission", b =>
                {
                    b.Property<long>("UserPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserPermissionId"));

                    b.Property<bool>("Granted")
                        .HasColumnType("bit");

                    b.Property<string>("PermissionKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserPermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.UserPreference", b =>
                {
                    b.Property<int>("UserPreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserPreferenceId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferenceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserPreferenceId");

                    b.HasIndex("UserId1");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.UserRole", b =>
                {
                    b.Property<long>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserRoleId"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.City", b =>
                {
                    b.HasOne("AdvanceCRM.Web.EF.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.ExcelImport", b =>
                {
                    b.HasOne("AdvanceCRM.Web.EF.Models.ExcelImportTemplate", "ExcelImportTemplate")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExcelImportTemplate");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.RolePermission", b =>
                {
                    b.HasOne("AdvanceCRM.Web.EF.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.UserPermission", b =>
                {
                    b.HasOne("AdvanceCRM.Web.EF.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.UserPreference", b =>
                {
                    b.HasOne("AdvanceCRM.Web.EF.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.UserRole", b =>
                {
                    b.HasOne("AdvanceCRM.Web.EF.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdvanceCRM.Web.EF.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AdvanceCRM.Web.EF.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
