[assembly: Serenity.ComponentModel.RegisterPermissionKey("Sales:Change Branch")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Sales:Re-open Sales")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Challan:Change Branch")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Challan:Re-open Challan")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Purchase:Change Branch")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Purchase:Re-open Purchase")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("PurchaseOrder:Re-open PurchaseOrder")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Attendance:Can Approve")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Enquiry:Clone")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Enquiry:Move to Quotation")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Enquiry:Re-open Enquiry")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Quotation:Clone")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Quotation:Move to Invoice")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Quotation:Move to Proforma")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Quotation:Re-open Quotation")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Proforma:Clone")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Proforma:Move to Invoice")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Proforma:Re-open Proforma")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("CMS:Move to Quotation")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("CMS:Re-open CMS")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("AMC:Re-open AMC")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Products:StockAlert")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Reports:Attendance")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Reports:Enquiry")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Reports:Quotation")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Reports:Inventory")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("Reports:Accounting")]
[assembly: Serenity.ComponentModel.RegisterPermissionKey("IVR:Click To Call")]
